# Generated by Django 4.1.7 on 2023-10-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.CreateModel(
            name='Task_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=75, verbose_name='Тема')),
                ('task', models.TextField(blank=True, null=True, verbose_name='Завдвння')),
                ('term', models.DateTimeField(db_index=True, null=True, verbose_name='Термін здачі')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубліковано')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_log.subject', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['-published'],
            },
        ),
    ]
